In [1]:
import os
import glob
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import pprint
import pyspark
import pyspark.sql.functions as F

from pyspark.sql.functions import col
from pyspark.sql.types import StringType, IntegerType, FloatType, DateType

import utils.data_processing_bronze_table
import utils.data_processing_silver_table
import utils.data_processing_gold_table

## set up pyspark session

In [2]:
# Initialize SparkSession
spark = pyspark.sql.SparkSession.builder \
    .appName("dev") \
    .master("local[*]") \
    .getOrCreate()

# Set log level to ERROR to hide warnings
spark.sparkContext.setLogLevel("ERROR")

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/05/13 08:09:26 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

## set up config

In [3]:
# set up config
snapshot_date_str = "2023-01-01"

start_date_str = "2023-01-01"
end_date_str = "2024-12-01"

In [4]:
# generate list of dates to process
def generate_first_of_month_dates(start_date_str, end_date_str):
    # Convert the date strings to datetime objects
    start_date = datetime.strptime(start_date_str, "%Y-%m-%d")
    end_date = datetime.strptime(end_date_str, "%Y-%m-%d")
    
    # List to store the first of month dates
    first_of_month_dates = []

    # Force the start date to the first day of the month
    current_date = datetime(start_date.year, start_date.month, 1)

    while current_date <= end_date:
        # Append the date in yyyy-mm-dd format
        first_of_month_dates.append(current_date.strftime("%Y-%m-%d"))
        
        # Move to the first of the next month
        if current_date.month == 12:
            current_date = datetime(current_date.year + 1, 1, 1)
        else:
            current_date = datetime(current_date.year, current_date.month + 1, 1)

    return first_of_month_dates

dates_str_lst = generate_first_of_month_dates(start_date_str, end_date_str)
dates_str_lst

['2023-01-01',
 '2023-02-01',
 '2023-03-01',
 '2023-04-01',
 '2023-05-01',
 '2023-06-01',
 '2023-07-01',
 '2023-08-01',
 '2023-09-01',
 '2023-10-01',
 '2023-11-01',
 '2023-12-01',
 '2024-01-01',
 '2024-02-01',
 '2024-03-01',
 '2024-04-01',
 '2024-05-01',
 '2024-06-01',
 '2024-07-01',
 '2024-08-01',
 '2024-09-01',
 '2024-10-01',
 '2024-11-01',
 '2024-12-01']

## Build Bronze Table

#### 1.1 LMS

In [5]:
# create bronze datalake
bronze_lms_directory = "datamart/bronze/lms/"

if not os.path.exists(bronze_lms_directory):
    os.makedirs(bronze_lms_directory)

In [6]:
# run bronze backfill for lms
for date_str in dates_str_lst:
    utils.data_processing_bronze_table.process_bronze_table(date_str, bronze_lms_directory, spark)

2023-01-01row count: 530
saved to: datamart/bronze/lms/bronze_loan_daily_2023_01_01.csv
2023-02-01row count: 1031
saved to: datamart/bronze/lms/bronze_loan_daily_2023_02_01.csv
2023-03-01row count: 1537
saved to: datamart/bronze/lms/bronze_loan_daily_2023_03_01.csv
2023-04-01row count: 2047
saved to: datamart/bronze/lms/bronze_loan_daily_2023_04_01.csv
2023-05-01row count: 2568
saved to: datamart/bronze/lms/bronze_loan_daily_2023_05_01.csv
2023-06-01row count: 3085
saved to: datamart/bronze/lms/bronze_loan_daily_2023_06_01.csv
2023-07-01row count: 3556
saved to: datamart/bronze/lms/bronze_loan_daily_2023_07_01.csv
2023-08-01row count: 4037
saved to: datamart/bronze/lms/bronze_loan_daily_2023_08_01.csv
2023-09-01row count: 4491
saved to: datamart/bronze/lms/bronze_loan_daily_2023_09_01.csv
2023-10-01row count: 4978
saved to: datamart/bronze/lms/bronze_loan_daily_2023_10_01.csv
2023-11-01row count: 5469
saved to: datamart/bronze/lms/bronze_loan_daily_2023_11_01.csv
2023-12-01row count: 5428
saved to: datamart/bronze/lms/bronze_loan_daily_2023_12_01.csv
2024-01-01row count: 5412
saved to: datamart/bronze/lms/bronze_loan_daily_2024_01_01.csv
2024-02-01row count: 5424
saved to: datamart/bronze/lms/bronze_loan_daily_2024_02_01.csv
2024-03-01row count: 5425
saved to: datamart/bronze/lms/bronze_loan_daily_2024_03_01.csv
2024-04-01row count: 5417
saved to: datamart/bronze/lms/bronze_loan_daily_2024_04_01.csv
2024-05-01row count: 5391
saved to: datamart/bronze/lms/bronze_loan_daily_2024_05_01.csv
2024-06-01row count: 5418
saved to: datamart/bronze/lms/bronze_loan_daily_2024_06_01.csv
2024-07-01row count: 5442
saved to: datamart/bronze/lms/bronze_loan_daily_2024_07_01.csv
2024-08-01row count: 5531
saved to: datamart/bronze/lms/bronze_loan_daily_2024_08_01.csv
2024-09-01row count: 5537
saved to: datamart/bronze/lms/bronze_loan_daily_2024_09_01.csv
2024-10-01row count: 5502
saved to: datamart/bronze/lms/bronze_loan_daily_2024_10_01.csv
2024-11-01row count: 5501
saved to: datamart/bronze/lms/bronze_loan_daily_2024_11_01.csv
2024-12-01row count: 5531
saved to: datamart/bronze/lms/bronze_loan_daily_2024_12_01.csv

In [7]:
# inspect output
utils.data_processing_bronze_table.process_bronze_table(date_str, bronze_lms_directory, spark).toPandas()

2024-12-01row count: 5531
saved to: datamart/bronze/lms/bronze_loan_daily_2024_12_01.csv

,loan_id,Customer_ID,loan_start_date,tenure,installment_num,loan_amt,due_amt,paid_amt,overdue_amt,balance,snapshot_date
0,CUS_0x100b_2024_03_01,CUS_0x100b,2024-03-01,10,9,10000,1000.0,1000.0,0.0,1000.0,2024-12-01
1,CUS_0x102e_2024_04_01,CUS_0x102e,2024-04-01,10,8,10000,1000.0,0.0,6000.0,8000.0,2024-12-01
2,CUS_0x1038_2024_10_01,CUS_0x1038,2024-10-01,10,2,10000,1000.0,1000.0,0.0,8000.0,2024-12-01
3,CUS_0x103e_2024_12_01,CUS_0x103e,2024-12-01,10,0,10000,0.0,0.0,0.0,10000.0,2024-12-01
4,CUS_0x1048_2024_02_01,CUS_0x1048,2024-02-01,10,10,10000,1000.0,0.0,9000.0,9000.0,2024-12-01
...,...,...,...,...,...,...,...,...,...,...,...
5526,CUS_0xfe3_2024_04_01,CUS_0xfe3,2024-04-01,10,8,10000,1000.0,1000.0,0.0,2000.0,2024-12-01
5527,CUS_0xff3_2024_06_01,CUS_0xff3,2024-06-01,10,6,10000,1000.0,1000.0,0.0,4000.0,2024-12-01
5528,CUS_0xff4_2024_12_01,CUS_0xff4,2024-12-01,10,0,10000,0.0,0.0,0.0,10000.0,2024-12-01
5529,CUS_0xff6_2024_10_01,CUS_0xff6,2024-10-01,10,2,10000,1000.0,1000.0,0.0,8000.0,2024-12-01
5530,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,9,10000,1000.0,1000.0,0.0,1000.0,2024-12-01

#### 1.2 Features

In [8]:
# create bronze feature datalake
bronze_feature_directory = "datamart/bronze/features/"

if not os.path.exists(bronze_feature_directory):
    os.makedirs(bronze_feature_directory)

In [9]:
# run bronze backfill for features
for date_str in dates_str_lst:
    utils.data_processing_bronze_table.process_bronze_features(
        date_str,
        bronze_feature_directory,
        spark
    )

clickstream - 2023-01-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2023_01_01.csv
clickstream - 2023-02-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2023_02_01.csv
clickstream - 2023-03-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2023_03_01.csv
clickstream - 2023-04-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2023_04_01.csv
clickstream - 2023-05-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2023_05_01.csv
clickstream - 2023-06-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2023_06_01.csv
clickstream - 2023-07-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2023_07_01.csv
clickstream - 2023-08-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2023_08_01.csv
clickstream - 2023-09-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2023_09_01.csv
clickstream - 2023-10-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2023_10_01.csv
clickstream - 2023-11-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2023_11_01.csv
clickstream - 2023-12-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2023_12_01.csv
clickstream - 2024-01-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2024_01_01.csv
clickstream - 2024-02-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2024_02_01.csv
clickstream - 2024-03-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2024_03_01.csv
clickstream - 2024-04-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2024_04_01.csv
clickstream - 2024-05-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2024_05_01.csv
clickstream - 2024-06-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2024_06_01.csv
clickstream - 2024-07-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2024_07_01.csv
clickstream - 2024-08-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2024_08_01.csv
clickstream - 2024-09-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2024_09_01.csv
clickstream - 2024-10-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2024_10_01.csv
clickstream - 2024-11-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2024_11_01.csv
clickstream - 2024-12-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2024_12_01.csv

In [10]:
# inspect output
utils.data_processing_bronze_table.process_bronze_features(date_str, bronze_feature_directory, spark).toPandas()

clickstream - 2024-12-01 row count: 8974
saved to: datamart/bronze/features/bronze_clickstream_2024_12_01.csv

,fe_1,fe_2,fe_3,fe_4,fe_5,fe_6,fe_7,fe_8,fe_9,fe_10,...,fe_13,fe_14,fe_15,fe_16,fe_17,fe_18,fe_19,fe_20,Customer_ID,snapshot_date
0,145,189,109,134,196,-37,101,82,111,24,...,65,249,200,185,-83,-18,-76,30,CUS_0x1037,2024-12-01
1,40,184,187,75,192,146,38,109,353,141,...,-14,193,125,117,215,91,33,255,CUS_0x1069,2024-12-01
2,98,121,180,200,95,48,59,194,76,84,...,167,101,92,185,98,68,-60,116,CUS_0x114a,2024-12-01
3,85,96,19,47,30,39,-32,210,-81,206,...,143,94,139,237,78,187,77,33,CUS_0x1184,2024-12-01
4,98,45,155,56,112,47,52,138,153,225,...,-43,142,121,10,189,110,264,241,CUS_0x1297,2024-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8969,414,22,72,57,142,192,11,139,24,63,...,179,91,20,189,-35,-19,15,66,CUS_0xdf6,2024-12-01
8970,116,-124,-108,212,-21,227,146,112,186,-65,...,38,226,319,98,9,152,17,14,CUS_0xe23,2024-12-01
8971,237,-3,-49,375,144,41,-170,324,19,266,...,7,102,64,191,124,220,231,75,CUS_0xe4e,2024-12-01
8972,5,67,211,83,207,-41,325,14,-18,41,...,109,266,28,157,131,116,101,131,CUS_0xedd,2024-12-01
8973,196,11,115,94,167,227,119,255,32,96,...,120,85,363,74,-26,107,104,186,CUS_0xfe4,2024-12-01

## Build Silver Table

In [ ]:
# create bronze datalake
silver_loan_daily_directory = "datamart/silver/loan_daily/"

if not os.path.exists(silver_loan_daily_directory):
    os.makedirs(silver_loan_daily_directory)

In [ ]:
# run silver backfill
for date_str in dates_str_lst:
    utils.data_processing_silver_table.process_silver_table(date_str, bronze_lms_directory, silver_loan_daily_directory, spark)

In [ ]:
utils.data_processing_silver_table.process_silver_table(date_str, bronze_lms_directory, silver_loan_daily_directory, spark).toPandas()

## EDA on credit labels

In [ ]:
# set dpd label definition
dpd = 30

# Path to the folder containing CSV files
folder_path = silver_loan_daily_directory

# Read all CSV files into a single DataFrame
files_list = [folder_path+os.path.basename(f) for f in glob.glob(os.path.join(folder_path, '*'))]
df = spark.read.option("header", "true").parquet(*files_list)

# filter only completed loans
df = df.filter(col("loan_start_date") < datetime.strptime("2024-01-01", "%Y-%m-%d"))

# create dpd flag if more than dpd
df = df.withColumn("dpd_flag", F.when(col("dpd") >= dpd, 1).otherwise(0))

# actual bads 
actual_bads_df = df.filter(col("installment_num") == 10)

# prepare for analysis
# df = df.filter(col("installment_num") < 10)

# visualise bad rate
pdf = df.toPandas()

# Group by col_A and count occurrences in col_B
grouped = pdf.groupby('mob')['dpd_flag'].mean()

# Sort the index (x-axis) of the grouped DataFrame
grouped = grouped.sort_index()

# Plotting
grouped.plot(kind='line', marker='o')

plt.title('DPD: '+ str(dpd))
plt.xlabel('mob')
plt.ylabel('bad rate')
plt.grid(True)
plt.show()

In [ ]:
df.show()

## Build gold table for labels

In [ ]:
# create bronze datalake
gold_label_store_directory = "datamart/gold/label_store/"

if not os.path.exists(gold_label_store_directory):
    os.makedirs(gold_label_store_directory)

In [ ]:
# run gold backfill
for date_str in dates_str_lst:
    utils.data_processing_gold_table.process_labels_gold_table(date_str, silver_loan_daily_directory, gold_label_store_directory, spark, dpd = 30, mob = 6)

In [ ]:
utils.data_processing_gold_table.process_labels_gold_table(date_str, silver_loan_daily_directory, gold_label_store_directory, spark, dpd = 30, mob = 6).dtypes

## inspect label store

In [ ]:
folder_path = gold_label_store_directory
files_list = [folder_path+os.path.basename(f) for f in glob.glob(os.path.join(folder_path, '*'))]
df = spark.read.option("header", "true").parquet(*files_list)
print("row_count:",df.count())

df.show()

In [ ]:
df.printSchema()